import React, { useState } from "react";
import AsyncSelect from "react-select/async";
import "../ipd/styles/WingModal.css";

const AddLabReport = ({ isOpen, onClose, onAddReport }) => {
  if (!isOpen) return null;

  const [form, setForm] = useState({
    uhid: "",
    testName: "",
    reportGeneratedBy: "",
    findings: "",
    unit: "",
    reference: "",
    method: "",
  });

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    onAddReport(form);
    onClose();
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <button type="button" onClick={onClose} className="closeBtn">
          X
        </button>
        <h3 style={{marginBottom: "30px"}}>Add New Lab Report</h3>
        <form onSubmit={handleSubmit}>
          <div className="form-row fg-group">
            <div className="form-group">
              <label>UHID:</label>
              <input
                type="text"
                name="uhid"
                onChange={handleChange}
                value={form.uhid}
              />
            </div>
            <div className="form-group">
              <label>Test Name:</label>
              <input
                type="text"
                name="testName"
                onChange={handleChange}
                value={form.testName}
              />
            </div>
          </div>

          <div className="form-row fg-group">
            <div className="form-group">
              <label>Report Generated By:</label>
              <input
                type="text"
                name="reportGeneratedBy"
                onChange={handleChange}
                value={form.reportGeneratedBy}
              />
            </div>
          </div>

          <div className="form-row fg-group">
            <div className="form-group">
              <label>Findings:</label>
              <textarea
                name="findings"
                onChange={handleChange}
                value={form.findings}
              />
            </div>
          </div>

          <div className="form-row fg-group">
            <div className="form-group">
              <label>Unit:</label>
              <input
                type="text"
                name="unit"
                onChange={handleChange}
                value={form.unit}
              />
            </div>
            <div className="form-group">
              <label>Reference:</label>
              <input
                type="text"
                name="reference"
                onChange={handleChange}
                value={form.reference}
              />
            </div>
          </div>

          <div className="form-row fg-group">
            <div className="form-group">
              <label>Method:</label>
              <input
                type="text"
                name="method"
                onChange={handleChange}
                value={form.method}
              />
            </div>
          </div>

          <button type="submit">Add Lab Report</button>
        </form>
      </div>
    </div>
  );
};

export default AddLabReport;
