import mongoose from "mongoose";

const patientAdmissionSchema = new mongoose.Schema({
  patientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Patient",
    required: true,
  },
  admissionDate: {
    type: Date,
  },
  referredBy: { type: String },
  referredById: { type: String },
  isNewReferral: { type: Boolean, default: false },
  timeOfAdmission: String,
  diagnosis: String,
  dischargeSummary: {
    dischargeDate: { type: Date },
    dischargeTime: String,
    statusAtDischarge: {
      type: String,
    },
    dischargeNotes: { type: String },
    numberOfDays: { type: Number },
    finalDiagnosis: { type: String },
    complications: { type: String },
    patientCondition: { type: String },
    keyInterventions: { type: String },
    dietaryInstructions: { type: String },
    activityRecommendations: { type: String },
    woundCareInstructions: { type: String },
    emergencyCareHow: { type: String },
    emergencyCareWhen: { type: String },
    procedures: [{ type: String }],
    // medications: [
    //   {
    //     name: { type: String },
    //     dosage: { type: String },
    //     frequency: { type: String },
    //   },
    // ],
    medications: String,
    followUpInstructions: { type: String },
    dischargeMode: { type: String },
    dischargingDoctor: { type: mongoose.Schema.Types.ObjectId, ref: "Doctor" },
  },
  doctorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Doctor",
    required: true,
  },
  doctorName: String,
  wardHistory: [
    {
      roomId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Room",
        required: true,
      },
      wingId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Wing",
        required: true,
      },
      bedName: { type: String, required: true },
      updatedAt: { type: Date, default: Date.now },
    },
  ],
  reasonForAdmission: {
    type: String,
  },
  referenceLetter: {
    type: String,
  },
  referenceDoctor: {
    type: String,
  },
  status: {
    type: String,
    enum: ["Admitted", "Discharged"],
    default: "Admitted",
  },
  nursingRate: {
    type: Number,
  },
  allergies: [
    {
      allergyName: {
        type: String,
      },
      allergyType: {
        type: String,
        enum: ["Food", "Drug", "Environmental", "Other"],
      },
      notes: {
        type: String,
        default: "",
      },
      doctorId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Doctor",
      },
      dateTime: {
        type: Date,
      },
    },
  ],
  physicalExamination: {
    vitalSigns: {
      bloodPressure: { type: String },
      heartRate: { type: String },
      temperature: { type: String },
      respiratoryRate: { type: String },
      oxygenSaturation: { type: String },
      bmi: { type: String },
    },
    doctorId: { type: mongoose.Schema.Types.ObjectId, ref: "Doctor" },
    sensorium: { type: String },
    pallor: { type: String },
    jaundice: { type: String },
    cyanosis: { type: String },
    oedema: { type: String },
    clubbing: { type: String },
    hair: { type: String },
    skin: { type: String },
    nails: { type: String },
    findings: { type: String },
    respiratorySystem: { type: String },
    urinarySystem: { type: String },
    nervousSystem: { type: String },
    cardiovascularSystem: { type: String },
    others: { type: String },
    updatedAt: { type: Date, default: Date.now },
  },
  investigations: {
    labTests: [
      {
        name: { type: String },
        dateTime: { type: Date },
        status: {
          type: String,
          enum: ["Pending", "Completed", "In Progress", "Canceled"],
          default: "Pending",
        },
        report: { type: String, default: "" },
      },
    ],
    updatedAt: { type: Date, default: Date.now },
  },
  chiefComplaints: [
    {
      complaint: { type: String},
      type: {
        type: String,
        enum: ["Major", "Minor"],
      },
      duration: {
        type: String,
      },
      description: {
        type: String,
        default: "",
      },
      updatedAt: {
        type: Date,
        default: Date.now,
      },
    },
  ],
  chemoNotes: [
    {
      plan: { type: String },
      diagnosis: { type: String },
      BSA: { type: Number },
      cycle: { type: Number },
      height: { type: Number },
      weight: { type: Number },
      date: { type: Date },
      specificInstruction: { type: String },
      sideEffects: { type: String },
      investigations: {
        cbcDiff: { type: String },
        echo: { type: String },
        familyCounselling: { type: String },
        ivAccess: { type: String },
        kft: { type: String },
        lft: { type: String },
        viralMarker: { type: String },
      },
      updatedAt: { type: Date, default: Date.now },
    },
  ],
  consumables: [
    {
      type: { type: String },
      name: { type: String },
      dosage: { type: String },
      duration: { type: String },
      quantity: { type: Number },
      doctor: { type: String },
      status: { type: String, enum: ["In Progress", "Completed", "Pending"] },
    },
  ],
  visitNotes: [
    {
      note: { type: String},
      doctorId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Doctor",
      },
      dateTime: { type: Date},
      updatedAt: { type: Date, default: Date.now },
    },
  ],
  obsGynae: {
    gravida: { type: String },
    para: { type: String },
    maritalHistory: { type: String },
    abortion: { type: String },
    complication: { type: String },
    initalExam: { type: Boolean, default: false },
    afp: { type: Boolean, default: false },
    gct: { type: Boolean, default: false },
    tubal: { type: Boolean, default: false },
    gbs: { type: Boolean, default: false },
    twentyWeeks: { type: Boolean, default: false },
    twentyEightWeeks: { type: Boolean, default: false },
    thirtySixWeeks: { type: Boolean, default: false},
    thirtyEightWeeks: { type: Boolean, default: false },
    fortyWeeks: { type: Boolean, default: false },
    ageOfOnset: { type: String },
    menopause: { type: String },
    uterus: { type: String },
    allergies: { type: String },
    pelvicExamination: { type: String },
    rectalExamination: { type: String },
    vaginalExamination: { type: String },
    breastExamination: { type: String },
    cervixExamination: { type: String },
    perAbdomen: { type: String },
    importantFindings: { type: String },
    hours: { type: String },
    show: { type: String },
    findings: { type: String },
    intact: { type: String },
    hoursAgo: { type: String },
    abdominalPalpatation: { type: String },
    heightOfFundus: { type: String },
    uterusCondition: { type: String },
    presentation: { type: String },
    position: { type: String },
    pelvisRelationship: { type: String },
    positionRate: { type: String },
    updatedAt: { type: Date, default: Date.now },
  },
  user: String,
  userEmail: String,
  userRole: String,
});

export default mongoose.model("PatientAdmission", patientAdmissionSchema);
